# Generated by Django 4.1.1 on 2022-09-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_myproject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myjobexperience',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
