# Generated by Django 4.1.1 on 2022-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_myjobexperience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myjobexperience',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
