# Generated by Django 4.1.1 on 2022-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_myproject_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='time_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
